config/routes.rb
CharCodex::Application.routes.draw do
	resources :comments, :adventures, :users, :backgrounds, :alignments,
						:encounters, :monsters, :terrains, :skills, :armors, :deities,
            :domains, :domain_powers, :spells, :feats, :gears, :weapons,
            :languages, :feats, :spell_schools, :rogue_talents

	resources :contents do
		resources :comments
  end

  resources :encounters do
    member do
      put '/battle_grid_update' => :battle_grid_update
    end
    collection do
      post '/battle_grid_create' => :battle_grid_create
    end
  end

  resources :races do
    member do
      get '/sheet_details' => :sheet_details
    end
  end

  resources :character_classes do
    member do
      get '/sheet_details' => :sheet_details
    end
  end

  resources :characters, :except => [:show] do
    member do
      post '/class_select' => :class_select
      put '/update_class_options' => :update_class_options
      post '/update_attributes_selection' => :update_attributes_selection
      post '/destroy_class_selection' => :destroy_class_selection
      post '/destroy_attributes_selection' => :destroy_attributes_selection
    end
  end

  match "logout" => "user_sessions#destroy"
	match "signup" => "users#signup"
	match "blog" => "contents#blog"

	match ":locale/:controller(/:action(/:id))"

  root :to => "contents#blog"

end

app/models/character.rb
class Character < ActiveRecord::Base
	belongs_to :user
	belongs_to :adventure
  belongs_to :alignment
  belongs_to :race
  belongs_to :deity

  has_many :skills, :through => :character_skills
  has_many :character_classes, :through => :character_character_classes
  has_many :armors, :through => :character_armors
  has_many :magic_armors, :through => :character_magic_armors
  has_many :weapons, :through => :character_weapons
  has_many :magic_weapons, :through => :character_magic_weapons
  has_many :magic_items, :through => :character_magic_items
  has_many :gears, :through => :character_gears

  has_many :character_skills
  has_many :character_character_classes, :dependent => :destroy
  has_many :character_armors
  has_many :character_magic_armors
  has_many :character_weapons
  has_many :character_magic_weapons
  has_many :character_magic_items
  has_many :character_gears

  has_and_belongs_to_many :feats
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :character_class_spells
  has_and_belongs_to_many :domains

	has_attached_file :photo, 		:styles => { :medium => "640x480>", :thumb => "100x100>" }
	has_attached_file :miniature, :styles => { :medium => "50x480>", :thumb => "50x50>" }

  validates :user_id, :presence => true

  accepts_nested_attributes_for :character_character_classes

  after_initialize :init_derived_data, :parse_features, :parse_traits, :parse_favored_classes, :parse_equipment,
                   :set_extra_cmd
  before_save :update_level

  attr_accessor :extra_initiative, :extra_hit_points, :extra_feats, :extra_skill_ranks, :movement,
                :armor_class, :extra_reflex, :extra_fortitude, :extra_will, :extra_cmb, :extra_cmd,
                :spell_resistance, :damage_reduction

  def init_derived_data
    @extra_initiative = 0
    @extra_hit_points = 0
    @extra_feats = 0
    @extra_skill_ranks = 0
    @movement = 30
    @extra_reflex = 0
    @extra_fortitude = 0
    @extra_will = 0
    @extra_cmb = 0
    @extra_cmd = 0
    @spell_resistance = 0
    @damage_reduction = 0
    @armor_class = {
        armor: 0,
        shield: 0,
        natural: 0,
        deflection: 0,
        dodge: 0,
        misc: 0
    }
  end

  def parse_features
    character_character_classes.group(:character_class_id).each do |c_c|
      c_c.character_class.character_class_features.each do |f|
        eval(f.bonus, binding) unless f.bonus.nil?
      end
    end
  end

  def parse_traits
    return if race.nil?

    race.race_traits.each do |trait|
      eval(trait.bonus, binding) unless trait.bonus.nil?
    end
  end

  def parse_favored_classes
    character_character_classes.each do |c_c|
      eval(c_c.favored_class_bonus.bonus, binding) if c_c.favored_class? and !c_c.favored_class_bonus.nil?
    end
  end

  def parse_equipment

  end

  def set_extra_cmd
    self.extra_cmd = armor_class[:deflection] + armor_class[:dodge]
  end

  def total_initiative
    dexterity_modifier + extra_initiative
  end

  def hit_points
    character_character_classes.map { |c| c.hp_gained}.reduce(:+) + constitution_modifier + extra_hit_points
  end

  def armor_class_dexterity
    dexterity_modifier
  end

  def total_armor_class
    10 + armor_class.values.reduce(:+) + armor_class_dexterity + race.size.armor_class_modifier
  end

  def touch_armor_class
    10 + armor_class_dexterity + armor_class[:dodge] + armor_class[:deflection] + race.size.armor_class_modifier
  end

  def flat_footed_armor_class
    10 + armor_class[:armor] + armor_class[:shield] + armor_class[:natural] + armor_class[:deflection] + race.size.armor_class_modifier
  end

  def total_fortitude
    base_fortitude + constitution_modifier + extra_fortitude
  end

  def total_reflex
    base_reflex + dexterity_modifier + extra_reflex
  end

  def total_will
    base_will + wisdom_modifier + extra_will
  end

  def base_attack_bonus
    @base_attack_bonus = 0
    self.character_class_levels.each do |c|
      @base_attack_bonus += (c.total_levels * c.character_class.base_multiplier).floor
    end
    @base_attack_bonus
  end

  def total_cmb
    base_attack_bonus + strength_modifier + race.size.combat_maneuver_modifier + extra_cmb
  end

  def total_cmd
    10 + base_attack_bonus + strength_modifier + dexterity_modifier + race.size.combat_maneuver_modifier + extra_cmd
  end

  def encumbered_movement
    if movement.eql?(20) and race.size.name.eql?('Small')
      15
    else
      20
    end
  end

  def character_class_levels
    self.character_character_classes.select("*, count(*) AS total_levels").group(:character_class_id).order(:created_at)
  end

  def last_created_class
    self.character_character_classes.order("created_at DESC").limit(1).first
  end

  def method_missing(method, *args, &block)
    if method.to_s =~ /^([a-z]+)_modifier$/
      ((self.send($1) - 10)/2).floor
    elsif method.to_s =~ /^base_([a-z]+)$/
      value = 0
      self.character_class_levels.each do |c|
        value += Level.find_by_level(c.total_levels).send("#{c.character_class.send("#{$1}?") ? 'good' : 'bad'}_saving_throw")
      end
      value
    else
      super
    end
  end

  private

  def update_level
    self.level = self.character_character_classes.count
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_filter do |controller|
    controller.restrict_access(3)
  end

  def new
    @character = Character.new

    respond_to do |format|
      format.html { render 'race_select', :layout => 'blank' }
    end
  end

  def edit
    @character = Character.find(params[:id])
    if @character.character_character_classes.empty?
      view = 'class_select'
      @character.character_character_classes.build
    elsif !@character.attributes_selected?
      view = 'attribute_select'
    elsif @character.last_created_class.completed_selection
      view = 'sheet'
    else
      view = 'edit_class_options'
      @selected_class_relation = @character.last_created_class
    end

    respond_to do |format|
      format.html { render view, :layout => 'blank' }
    end
  end

  # Creates a character after the race has been selected.
  def create
    @character = Character.new(params[:character])
    @character.user_id = current_user.id
    params[:success] = @character.save

    respond_to do |format|
      format.js { render :next_step }
    end
  end

  def update
    @character = Character.find(params[:id])
    params[:success] = @character.update_attributes(params[:character])
    params[:view] ||= :update

    respond_to do |format|
      format.js { render params[:view] }
    end
  end

  def destroy_attributes_selection
    @character = Character.find(params[:id])
    @character.attributes_selected = false
    params[:success] = @character.save

    respond_to do |format|
      format.js { render :next_step }
    end
  end

  def update_attributes_selection
    @character = Character.find(params[:id])
    unless params[:arbitrary_attribute].nil?
      params[:character][params[:arbitrary_attribute].to_sym] = (params[:character][params[:arbitrary_attribute].to_sym].to_i + 2).to_s
    end

    @character.race.race_attributes.each do |r_a|
      attr = r_a.attribute.name.downcase.to_sym
      params[:character][attr] = (params[:character][attr].to_i + r_a.value).to_s
    end

    params[:success] = @character.update_attributes(params[:character])

    respond_to do |format|
      format.js { render :next_step }
    end
  end

  def destroy_class_selection
    @character = Character.find(params[:id])
    @character.last_created_class.destroy

    render :nothing => true
  end

  def update_class_options
    @character = Character.find(params[:id])
    params[:success] = @character.last_created_class.update_attributes(params[:character_character_class])

    respond_to do |format|
      format.js { render :next_step }
    end
  end

	active_scaffold :character do |config|
    config.actions.exclude :show, :create, :update
    config.list.columns = [:name, :race, :character_classes, :level, :adventure]
    config.search.columns = [:name]

    config.columns[:adventure].clear_link
    config.columns[:race].clear_link
    config.columns[:character_classes].clear_link

    config.action_links.add :new, :label => I18n.t('active_scaffold.create_new'), :page => true, :type => :collection,
                            :html_options => CharactersHelper::lightview_options

    config.action_links.add :edit, :label => I18n.t('active_scaffold.edit'), :page => true, :type => :member,
                            :html_options => CharactersHelper::lightview_options
  end

  protected

  def conditions_for_collection
    ['characters.user_id = ?', current_user.id]
  end
end

app/helpers/characters_helper.rb
module CharactersHelper

  def self.lightview_options
    {
        :class => 'lightview',
        :'data-lightview-type' => 'ajax',
        :'data-lightview-options' => YAML::load_file("#{Rails.root}/config/lightview.yml").to_json.gsub(/^{|}$/, "").gsub(/\\|"/, "")
    }
  end

  def attribute_modifier(attr)
    modifier = @character.send("#{attr}_modifier")
    "#{'+' if modifier >= 0}#{modifier}"
  end

  def character_movement(options={})
    options[:encumbered] ||= false
    value = @character.send("#{'encumbered_' if options[:encumbered]}movement")

    "#{value} #{t(:feet)} (#{value/5} #{t(:squares)})"
  end

  def adventure_field
    @character.adventure.nil? ? '-' : @character.adventure.name
  end

  def character_race_options(selected)
    options_for_select Race.all.map{ |r| [r.name, r.id] }, selected
  end

  def character_class_options(selected)
    options_for_select CharacterClass.all.map{ |r| [r.name, r.id] }, selected
  end

  def favored_class_bonus_options
    options_for_select FavoredClassBonus.all.map{ |r| [r.benefit, r.id] }
  end

  def fantasy_type_options
    options_for_select [['Low Fantasy (10)', 10], ['Standard Fantasy (15)', 15],
                        ['High Fantasy (20)', 20], ['Epic Fantasy (25)', 25], [t(:random), -1]], 15
  end

  def attributes_array
    [:strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma]
  end

  def attribute_options
    options_for_select(Array.new(6) do |i|
      attr = attributes_array[i]
      [t("activerecord.attributes.character.#{attr}"), attr.to_s]
    end)
  end

  def alignment_options
    options_for_select Alignment.all.map{ |a| [a.name, a.id] }.unshift(['', nil]), @character.alignment_id
  end

  def deity_options
    options_for_select Deity.all.map{ |a| [a.name, a.id] }.unshift(['', nil]), @character.deity_id
  end

  def gender_options
    options_for_select [[t(:male), t(:male)], [t(:female), t(:female)]]
  end

  def character_character_classes_column(record)
    record.character_character_classes.select('*, count(*) AS total_level').group(:character_class_id).map do |c|
      "#{c.character_class.name} #{c.total_level}"
    end.join(" / ")
  end

end

app/views/characters/_attribute_select_field.html.erb
<div class="attribute-form-field" data-attr="<%= attr.to_s %>" id="<%= attr.to_s %>_field">
  <div class="buttons">
    <button class="btn btn-success increase_attribute">+</button>
    <button class="btn btn-danger decrease_attribute">-</button>
  </div>
  <%= f.text_field attr, :disabled => true, :value => 10 %>
  <%= f.label attr, "#{t("activerecord.attributes.character.#{attr}")} (#{attr.slice(0..2).upcase})" %>

  <span class="race-attribute">
    <%= "#{'+' if race_attributes[attr] > 0}#{race_attributes[attr]}" unless race_attributes[attr].nil? %>
  </span>
</div>

app/views/characters/_saving_throw_field.html.erb
<div class="sheet-field saving-throw-field">
  <%= label_tag save, t("character_sheet.field.#{save}") %>
  <span class="equal">=</span>
  <div class="sheet-box-field-container">
    <span class="sheet-box-field">
      <%= @character.send("base_#{save}") %>
    </span>
    <span class="sheet-box-field-label">Base</span>
  </div>
  <span class="plus">+</span>
  <div class="sheet-box-field-container">
    <span class="sheet-box-field">
      <%= @character.send("#{attr}_modifier") %>
    </span>
    <span class="sheet-box-field-label">
      <%= "#{t("activerecord.attributes.character.#{attr}").to_s.capitalize.slice(0..2)}." %>
    </span>
  </div>
  <span class="plus">+</span>
  <div class="sheet-box-field-container">
    <span class="sheet-box-field">
      <%= @character.send("extra_#{save}") %>
    </span>
    <span class="sheet-box-field-label">Misc.</span>
  </div>
  <span class="equal">=</span>
  <div class="sheet-box-field-container result">
    <span class="sheet-box-field">
      <%= @character.send("total_#{save}") %>
    </span>
    <span class="sheet-box-field-label">&nbsp;</span>
  </div>
</div>

app/views/characters/_transition.js.erb
<% if params[:success] %>
  // Load the character class selection box
  Lightview.show({
    url: '<%= send(route_helper, @character.id) %>',
    type: 'ajax',
    options: {<%=raw YAML::load_file("#{Rails.root}/config/lightview.yml").to_json.gsub(/^{|}$/, "").gsub(/\\|"/, "") %>}
  });
<% else %>
  alert('<%= "#{t('character_sheet.forms.error')}:\n #{show_errors(@character)}" %>');
<% end %>

app/views/characters/attribute_select.html.erb
<% have_arbitrary_attributes = (!@character.race.arbitrary_attributes.nil? and @character.race.arbitrary_attributes > 0) %>
<div id='attribute-select-container'>
  <%= hidden_field_tag :sheet_changed, true %>

  <div class="attribute-select-header">
    <h2><%= t('character_sheet.forms.attribute_select.title') %></h2>
    <h3><%= t('character_sheet.forms.attribute_select.description') %></h3>

    <div class="attribute-point-select">
      <%= label_tag :fantasy_type, t('character_sheet.attributes.fantasy_type') %>
      <%= select_tag :fantasy_type, fantasy_type_options, :disabled => ('disabled' if have_arbitrary_attributes) %>
    </div>
  </div>

  <div class="attribute-select-body">
    <% race_attributes = Hash[*@character.race.race_attributes.map { |r| [r.attribute.name.downcase.to_sym, r.value] }.flatten]  %>
    <%= form_for @character, :url => update_attributes_selection_character_path , :method => :post, :remote => true, :html => { :class => "#{'disabled' if have_arbitrary_attributes}" } do |f| %>
      <%= hidden_field_tag :attributes_set, false %>
      <% if have_arbitrary_attributes %>
        <div class="disable"></div>
        <%= hidden_field_tag :arbitrary_attribute %>
      <% end %>
      <%= hidden_field_tag :view, 'next_step'  %>
      <%= f.hidden_field :attributes_selected, :value => true %>

      <% attributes_array.each do |attr| %>
        <%= render :partial => 'attribute_select_field', :locals => { :f => f, :attr => attr, :race_attributes => race_attributes } %>
      <% end %>
    <% end %>

    <div id="attribute-points"><%= t('character_sheet.attributes.remaining_points') %>: <strong>15</strong></div>

    <% if have_arbitrary_attributes %>
      <div id="arbitrary-attribute-select-container">
        <%= label_tag :arbitrary_attribute_select, t('character_sheet.attributes.arbitrary_select') %>
        <%= select_tag :arbitrary_attribute_select, attribute_options %>
        <button class="btn btn-success btn-small">OK</button>
      </div>
    <% end %>
  </div>

  <div class="attribute-select-footer">
    <button class="btn btn-primary submit"><%= t('active_scaffold._select_') %></button>
    <button class="btn back close_callback" data-characterclassid="<%= @character.last_created_class.character_class_id %>" data-characterid="<%= @character.id %>"><%= t('character_sheet.buttons.back_class_select') %></button>
  </div>
</div>

app/views/characters/class_select.html.erb
<% selected_class = params[:selected_class].nil? ? CharacterClass.first : CharacterClass.find(params[:selected_class]) %>
<div id='class-select-container'>
  <%= hidden_field_tag :sheet_changed, true %>

  <div class="class-select-header">
    <h2><%= t('character_sheet.forms.class_select.title') %></h2>

    <%= form_for @character, :remote => true do |f| %>
      <%= hidden_field_tag :view, 'next_step'  %>
      <%= f.fields_for :character_character_classes do |c| %>
        <div class="class-select-form-field">
          <%= c.select :character_class_id, character_class_options(selected_class.id) %>
        </div>
        <div class="class-select-form-field">
          <%= c.label :favored_class, t('activerecord.attributes.character_character_class.favored_class') %>
          <%= c.check_box :favored_class, :checked => 'checked' %>
          <span class="hint">Sim</span>
        </div>
      <% end %>
    <% end %>
  </div>

  <div class="class-select-body">
    <%= render :partial => 'character_classes/details', locals: { selected_class: selected_class } %>
  </div>

  <div class="class-select-footer">
    <button class="btn btn-primary submit"><%= t('active_scaffold._select_') %></button>
    <button class="btn back" data-raceid="<%= @character.race_id %>" data-characterid="<%= @character.id %>"><%= t('character_sheet.buttons.back_race_select') %></button>
  </div>

</div>

app/views/characters/class_select.js.erb
<%= render :partial => 'transition', :locals => { :route_helper => 'edit_character_path' } %>

app/views/characters/edit_class_options.html.erb
<div id="class-options-container">
  <%= hidden_field_tag :sheet_changed, true %>

  <div class="class-options-header">
    <h2>
      <%= t('character_sheet.forms.class_options.title',
              :class => @selected_class_relation.character_class.name,
              :level => @selected_class_relation.level) %>
    </h2>
    <h3>
      <%= t('character_sheet.forms.class_options.description') %>
    </h3>
  </div>

  <div class="class-options-body">

    <div class="class-options-form">
      <%= form_for @selected_class_relation, :url => update_class_options_character_path, :remote => true do |f| %>
        <%= f.hidden_field :completed_selection, :value => true %>
        <% hit_dice = f.object.character_class.hit_dice %>
        <% if f.object.favored_class? %>
          <div class="class-options-form-field">
            <%= f.label :favored_class_bonus_id, "#{t('activerecord.attributes.character_character_class.favored_class_bonus')}:" %>
            <%= f.select :favored_class_bonus_id, options_for_select(favored_class_bonus_options) %>
          </div>
        <% end %>
        <div class="class-options-form-field" id="hp_gained-field">
          <%= f.label :hp_gained, "#{t('activerecord.attributes.character_character_class.hp_gained')}:" %>
          <%= f.text_field :hp_gained %>
          <span class="hint"><%= t('character_sheet.character_class.hit_dice', :value => hit_dice.name).html_safe %></span>
          <div class="buttons">
            <button class='average-roll btn btn-small btn-primary' data-value='<%= (hit_dice.value/2).floor + 1 %>'><%= t('character_sheet.dice.use_average', :value => (hit_dice.value/2).floor + 1) %></button>
            <button class='random-roll btn btn-small btn-success' data-dice='<%= hit_dice.value %>'><%= t('character_sheet.dice.use_random') %></button>
          </div>
        </div>
      <% end %>
    </div>

    <div class="class-features-description">
      <h4><%= t('character_sheet.character_class.gained_features') %>:</h4>
      <ul>
        <% @selected_class_relation.gained_features.each do |feature| %>
          <li>
            <%= feature.name %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="class-options-footer">
    <button class="btn btn-primary submit"><%= t('active_scaffold._select_') %></button>
    <button class="btn back close_callback" data-characterid="<%= @character.id %>"><%= t('character_sheet.buttons.back_attributes_select') %></button>
  </div>
</div>

app/views/characters/list.html.erb
<div id="content-t">
	<%= t(:character_manager) %>
</div>
<%= render :super %>

app/views/characters/next_step.js.erb
<%= render :partial => 'transition', :locals => { :route_helper => 'edit_character_path' } %>

app/views/characters/race_select.html.erb
<% selected_race = params[:selected_race].nil? ? Race.first : Race.find(params[:selected_race]) %>
<div id='race-select-container'>
  <%= hidden_field_tag :sheet_changed, true %>

  <div class="race-select-header">
    <h2><%= t('character_sheet.forms.race_select.title') %></h2>

    <%= form_for @character, :remote => true, :method => :post do |f| %>
      <%= f.select :race_id, character_race_options(selected_race.id) %>
    <% end %>
  </div>

  <div class="race-select-body">
    <%= render :partial => 'races/details', locals: { selected_race: selected_race } %>
  </div>

  <div class="race-select-footer">
    <button class="btn btn-primary submit"><%= t('active_scaffold._select_') %></button>
    <button class="btn close_lightview"><%= t('active_scaffold.cancel') %></button>
  </div>
</div>

app/views/characters/sheet.html.erb
<div id='character-sheet-inner' class='tabbable'>
  <%= hidden_field_tag :sheet_changed, false %>

  <div class="sheet-header">
    <div class="sheet-saving-indicator">
      <%= t('character_sheet.saving') %>
    </div>
    <%= image_tag 'pathfinder_logo.jpg' %>
    <ul class="nav nav-tabs">
      <li>
        <%= link_to t('character_sheet.tabs.spells'), '#spells', data: { toggle: 'tab' } %>
      </li>
      <li>
        <%= link_to t('character_sheet.tabs.gear'), '#gear', data: { toggle: 'tab' } %>
      </li>
      <li>
        <%= link_to t('character_sheet.tabs.feats_and_skills'), '#feats_and_skills', data: { toggle: 'tab' } %>
      </li>
      <li class="active">
        <%= link_to t('character_sheet.tabs.basic_info'), '#basic-info', data: { toggle: 'tab' } %>
      </li>
    </ul>
  </div>

  <%= form_for @character, :remote => true do |f| %>
    <div class="sheet-body tab-content">
        <div class="tab-pane active" id="basic-info">
          <%= render :partial => 'basic_info', :locals => { f: f } %>
        </div>
        <div class="tab-pane" id="feats_and_skills">
          feats and skills
        </div>
        <div class="tab-pane" id="gear">
          gear
        </div>
        <div class="tab-pane" id="spells">
    spells
        </div>
    </div>
  <% end %>

</div>

app/views/characters/update.js.erb
$(".sheet-saving-indicator").hide();

<% if params[:success] %>
  $('#sheet_changed').val(true);
<% else %>
  alert('Ocorreu um erro ao tentar salvar a ficha do seu personagem. Por favor, tente novamente mais tarde.');
<% end %>